#!/bin/bash

alias cp='cp -i'
alias ctop='docker run --rm -ti --name=ctop -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest'
alias dc='docker-compose -f /root/docker/docker-compose.yml'
alias egrep='egrep --color=auto'
alias exut='exit'
alias exot='exit'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias less='less -r'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls -F --color=auto'
alias mv='mv -i'
alias rm='rm -i'
alias pane='tmux display -p "#P"'
alias pylint='pylint --rcfile=~/.pylintrc'
alias rsyncme='rsync -vaogHDSxP --no-inc-recursive'
alias sagent="sshagent_init"
alias fix_title="echo -en '\033k  \033\\'"
alias vi='vim'
