#!/bin/sh

alias cp='cp -i'
alias exut='exit'
alias exot='exit'
alias irssi='tmux rename-window irssi; sudo -u elliott HOME=/home/elliott irssi'
alias less='less -r'
alias ls='ls -F --color=yes'
alias mv='mv -i'
alias rm='rm -i'
alias rsyncme='rsync -vaogHDSxP --no-inc-recursive'
alias sagent="sshagent_init"
alias vi='vim'
