#!/bin/sh

EDITOR=/usr/bin/vim
HOSTNAME=$(hostname -f)
LANG=en_US.UTF-8
LANGUAGE=${LANG}
OS_TYPE=$(uname)
PATH=${HOME}/scripts:/snap/bin:/sbin:${PATH}
unset USERNAME
if [ "${OS_TYPE}" = "Darwin" ]; then
  LESSCLOSE="lessclose.sh %s %s"
  LESSOPEN="|lesspipe.sh %s"
  local HB=${HOME}/homebrew
  PATH_NOHB=${PATH}
  PATH=${HB}/bin:${HB}/sbin:${HB}/opt/coreutils/libexec/gnubin:${PATH}
else
  [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
fi

if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || \
    eval "$(dircolors -b)"
fi

export EDITOR HOSTNAME LANG LANGUAGE LESSCLOSE LESSOPEN LS_COLORS OS_TYPE PATH PATH_NOHB TERM
